### ISSUE TITLE
Candy-2.0.1 error hiding bar in combat

### ISSUE THREAD

**Issue by ceylina** [Sonaza/Candy#5]
1x [ADDON_ACTION_BLOCKED] AddOn 'Candy' tried to call the protected function 'CandyToyBoxQFrame:Hide()'.
!BugGrabber\BugGrabber.lua:573: in function <!BugGrabber\BugGrabber.lua:573>
[C]: in function `Hide'
Candy\core.lua:284: in function <Candy\core.lua:283>

I am sorry I do not have more detailed information but I was in an mythic dungeon when this error popped. I have a few bars that hide in combat

**Comment by Sonaza** [comment]
Using toy box items requires secure frames. If the DataBroker tooltip by ToyBoxQ has some secure frames then hiding them will become impossible while in combat.

I am not sure if it's possible for me to fix this, since it is caused by an external addon. Going to look into it anyway.

**Comment by Sonaza** [comment]
Seems ToyBoxQ actually creates additional frame directly over the DataBroker parent frame.

**Comment by Sonaza** [comment]
I cannot fix or prevent ToyBoxQ from doing its thing, like displaying tooltips or possibly causing its own protected frame errors since it is using completely different frames.

I fixed the hide error in Candy by instead making frames unclickable and transparent while in combat. This should be enough.

**Comment by ceylina** [comment]
Thank you and toyboxq... should have known. It was late and I was fixing other addons so I completely missed that it was that causing it.
